//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realestate.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.Citizen = new HashSet<Citizen>();
        }
    
        public int IDestate { get; set; }
        public string Address { get; set; }
        public Nullable<int> Prescribed { get; set; }
        public Nullable<int> HousingArea { get; set; }
        public Nullable<double> Rent { get; set; }
        public Nullable<int> IDtype { get; set; }
        public Nullable<double> CostForMeter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citizen> Citizen { get; set; }
        public virtual Type Type { get; set; }
    }
}
